### ISSUE TITLE
Incompatible with native AJAX cart [2.2.3]

### ISSUE THREAD

**Issue by adamj88** [meanbee/magento2-infinitescroll#8]
Unsure if related to #4 

On Magento OS 2.2.3, when pressing "Add to Cart" on a product from the grid the page is reloaded and the product added to cart rather than the default behaviour of submitting an AJAX request and showing the mini cart dropdown.

Believe the affected code is: https://github.com/meanbee/magento2-infinitescroll/blob/master/src/view/frontend/templates/product/list.phtml#L88-L96

```html
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
```

In 2.2.3 this is: https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Catalog/view/frontend/templates/product/list.phtml#L120-L130

```html
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
```

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
